const events = {
  INCREMENTAR_HOMENS: "INCREMENTAR_HOMENS_EVENTO",
  DIMINUIR_HOMENS: "DIMINUIR_HOMENS_EVENTO",
  INCREMENTAR_MULHERES: "INCREMENTAR_MULHERES_EVENTO",
  DIMINUIR_MULHERES: "DIMINUIR_MULHERES_EVENTO",
  INCREMENTAR_CRIANCAS: "INCREMENTAR_CRIANCAS_EVENTO",
  DIMINUIR_CRIANCAS: "DIMINUIR_CRIANCAS_EVENTO",
  CALCULAR: "CALCULO_SOLICITADO_EVENTO",
  CALCULO_REALIZADO: "CALCULO_REALIZADO_EVENTO",
  REGISTRAR: "REGISTRAR",
};
